package com.otectus.runicskills.handler;

import com.otectus.runicskills.RunicSkills;
import com.otectus.runicskills.config.Configuration;
import com.otectus.runicskills.config.models.LockItem;
import com.otectus.runicskills.config.LockItemListGroup;
import dev.isxander.yacl3.config.v2.api.ConfigClassHandler;
import dev.isxander.yacl3.config.v2.api.SerialEntry;
import dev.isxander.yacl3.config.v2.api.autogen.ListGroup;
import dev.isxander.yacl3.config.v2.api.serializer.GsonConfigSerializerBuilder;
import net.minecraft.resources.ResourceLocation;

import java.util.List;

public class HandlerLockItemsConfig {

    public static ConfigClassHandler<HandlerLockItemsConfig> HANDLER = ConfigClassHandler.createBuilder(HandlerLockItemsConfig.class)
            .id(new ResourceLocation(RunicSkills.MOD_ID, "config"))
            .serializer(config -> GsonConfigSerializerBuilder.create(config)
                    .setPath(Configuration.getAbsoluteDirectory().resolve("runicskills.lockItems.json5"))
                    .setJson5(true)
                    .build())
            .build();

    @SerialEntry(comment = "Lock item list")
    @ListGroup(controllerFactory = LockItemListGroup.class, valueFactory = LockItemListGroup.class, addEntriesToBottom = true)
    public List<LockItem> lockItemList = List.of(
            new LockItem("minecraft:anvil", new LockItem.Skill("building", 12)),
            new LockItem("minecraft:chipped_anvil", new LockItem.Skill("building", 12)),
            new LockItem("minecraft:damaged_anvil", new LockItem.Skill("building", 12)),
            new LockItem("minecraft:brewing_stand", new LockItem.Skill("wisdom", 12), new LockItem.Skill("magic", 12), new LockItem.Skill("intelligence", 12)),
            new LockItem("minecraft:enchanting_table", new LockItem.Skill("magic", 12)),
            new LockItem("minecraft:beacon", new LockItem.Skill("building", 20)),
            new LockItem("minecraft:end_crystal", new LockItem.Skill("magic", 30), new LockItem.Skill("building", 24)),
            new LockItem("minecraft:ender_chest", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:respawn_anchor", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:white_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:light_gray_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:gray_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:black_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:brown_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:red_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:orange_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:yellow_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:lime_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:green_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:cyan_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:light_blue_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:blue_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:purple_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:magenta_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:pink_shulker_box", new LockItem.Skill("magic", 20)),
            new LockItem("minecraft:dragon_egg", new LockItem.Skill("magic", 30)),
            new LockItem("minecraft:wither_skeleton_skull", new LockItem.Skill("magic", 8), new LockItem.Skill("building", 8)),
            new LockItem("minecraft:lodestone", new LockItem.Skill("building", 16), new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:smithing_table", new LockItem.Skill("building", 20), new LockItem.Skill("intelligence", 16)),
            new LockItem("minecraft:grindstone", new LockItem.Skill("building", 16), new LockItem.Skill("intelligence", 16)),
            new LockItem("minecraft:cartography_table", new LockItem.Skill("building", 12), new LockItem.Skill("intelligence", 12)),
            new LockItem("minecraft:stonecutter", new LockItem.Skill("building", 6), new LockItem.Skill("strength", 6)),
            new LockItem("minecraft:smoker", new LockItem.Skill("building", 6)),
            new LockItem("minecraft:blast_furnace", new LockItem.Skill("building", 6)),
            new LockItem("minecraft:loom", new LockItem.Skill("building", 8), new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:name_tag", new LockItem.Skill("intelligence", 10)),
            new LockItem("minecraft:fishing_rod", new LockItem.Skill("fortune", 4)),
            new LockItem("minecraft:bone_meal", new LockItem.Skill("fortune", 12)),
            new LockItem("minecraft:shears", new LockItem.Skill("building", 4)),
            new LockItem("minecraft:lead", new LockItem.Skill("intelligence", 4)),
            new LockItem("minecraft:spyglass", new LockItem.Skill("intelligence", 4), new LockItem.Skill("dexterity", 4)),
            new LockItem("minecraft:brush", new LockItem.Skill("intelligence", 12)),
            new LockItem("minecraft:fire_charge", new LockItem.Skill("intelligence", 4)),
            new LockItem("minecraft:flint_and_steel", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:redstone", new LockItem.Skill("intelligence", 4)),
            new LockItem("minecraft:redstone_torch", new LockItem.Skill("intelligence", 4)),
            new LockItem("minecraft:repeater", new LockItem.Skill("intelligence", 4)),
            new LockItem("minecraft:comparator", new LockItem.Skill("intelligence", 4)),
            new LockItem("minecraft:writable_book", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:written_book", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:tnt", new LockItem.Skill("intelligence", 12)),
            new LockItem("minecraft:lectern", new LockItem.Skill("intelligence", 6), new LockItem.Skill("building", 4)),
            new LockItem("minecraft:ender_pearl", new LockItem.Skill("magic", 8)),
            new LockItem("minecraft:ender_eye", new LockItem.Skill("magic", 16)),
            new LockItem("minecraft:bow", new LockItem.Skill("dexterity", 4), new LockItem.Skill("strength", 2)),
            new LockItem("minecraft:crossbow", new LockItem.Skill("dexterity", 6), new LockItem.Skill("strength", 4)),
            new LockItem("minecraft:saddle", new LockItem.Skill("dexterity", 6)),
            new LockItem("minecraft:elytra", new LockItem.Skill("dexterity", 30)),
            new LockItem("minecraft:firework_rocket", new LockItem.Skill("dexterity", 20), new LockItem.Skill("intelligence", 20)),
            new LockItem("minecraft:experience_bottle", new LockItem.Skill("magic", 12), new LockItem.Skill("fortune", 10)),
            new LockItem("minecraft:wheat_seeds", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:cocoa_beans", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:pumpkin_seeds", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:melon_seeds", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:beetroot_seeds", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:torchflower_seeds", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:pitcher_pod", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:glow_berries", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:sweet_berries", new LockItem.Skill("intelligence", 6)),
            new LockItem("minecraft:nether_wart", new LockItem.Skill("intelligence", 10), new LockItem.Skill("magic", 8)),
            new LockItem("minecraft:egg", new LockItem.Skill("constitution", 4)),
            new LockItem("minecraft:frogspawn", new LockItem.Skill("intelligence", 12), new LockItem.Skill("constitution", 16)),
            new LockItem("minecraft:turtle_egg", new LockItem.Skill("intelligence", 12), new LockItem.Skill("constitution", 16)),
            new LockItem("minecraft:sniffer_egg", new LockItem.Skill("intelligence", 12), new LockItem.Skill("constitution", 16)),
            new LockItem("minecraft:oak_sapling", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:spruce_sapling", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:birch_sapling", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:jungle_sapling", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:acacia_sapling", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:dark_oak_sapling", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:mangrove_propagule", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:cherry_sapling", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:azalea", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:flowering_azalea", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:brown_mushroom", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:red_mushroom", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:crimson_fungus", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:warped_fungus", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:bamboo", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:sugar_cane", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:cactus", new LockItem.Skill("intelligence", 8)),
            new LockItem("minecraft:chorus_plant", new LockItem.Skill("intelligence", 12)),
            new LockItem("minecraft:chorus_flower", new LockItem.Skill("intelligence", 12)),
            new LockItem("minecraft:shield", new LockItem.Skill("endurance", 4), new LockItem.Skill("constitution", 4)),
            new LockItem("minecraft:chainmail_helmet", new LockItem.Skill("endurance", 4)),
            new LockItem("minecraft:chainmail_chestplate", new LockItem.Skill("endurance", 4)),
            new LockItem("minecraft:chainmail_leggings", new LockItem.Skill("endurance", 4)),
            new LockItem("minecraft:chainmail_boots", new LockItem.Skill("endurance", 4)),
            new LockItem("minecraft:iron_helmet", new LockItem.Skill("endurance", 8)),
            new LockItem("minecraft:iron_chestplate", new LockItem.Skill("endurance", 8)),
            new LockItem("minecraft:iron_leggings", new LockItem.Skill("endurance", 8)),
            new LockItem("minecraft:iron_boots", new LockItem.Skill("endurance", 8)),
            new LockItem("minecraft:golden_helmet", new LockItem.Skill("endurance", 6), new LockItem.Skill("magic", 6)),
            new LockItem("minecraft:golden_chestplate", new LockItem.Skill("endurance", 6), new LockItem.Skill("magic", 6)),
            new LockItem("minecraft:golden_leggings", new LockItem.Skill("endurance", 6), new LockItem.Skill("magic", 6)),
            new LockItem("minecraft:golden_boots", new LockItem.Skill("endurance", 6), new LockItem.Skill("magic", 6)),
            new LockItem("minecraft:diamond_helmet", new LockItem.Skill("endurance", 16)),
            new LockItem("minecraft:diamond_chestplate", new LockItem.Skill("endurance", 16)),
            new LockItem("minecraft:diamond_leggings", new LockItem.Skill("endurance", 16)),
            new LockItem("minecraft:diamond_boots", new LockItem.Skill("endurance", 16)),
            new LockItem("minecraft:netherite_helmet", new LockItem.Skill("endurance", 24)),
            new LockItem("minecraft:netherite_chestplate", new LockItem.Skill("endurance", 24)),
            new LockItem("minecraft:netherite_leggings", new LockItem.Skill("endurance", 24)),
            new LockItem("minecraft:netherite_boots", new LockItem.Skill("endurance", 24)),
            new LockItem("minecraft:turtle_helmet", new LockItem.Skill("endurance", 6), new LockItem.Skill("dexterity", 6)),
            new LockItem("minecraft:golden_horse_armor", new LockItem.Skill("endurance", 4), new LockItem.Skill("dexterity", 4)),
            new LockItem("minecraft:iron_horse_armor", new LockItem.Skill("endurance", 6), new LockItem.Skill("dexterity", 6)),
            new LockItem("minecraft:diamond_horse_armor", new LockItem.Skill("endurance", 12), new LockItem.Skill("dexterity", 12)),
            new LockItem("minecraft:totem_of_undying", new LockItem.Skill("constitution", 16), new LockItem.Skill("magic", 12)),
            new LockItem("minecraft:trident", new LockItem.Skill("strength", 20), new LockItem.Skill("dexterity", 18)),
            new LockItem("minecraft:iron_hoe", new LockItem.Skill("building", 8)),
            new LockItem("minecraft:iron_shovel", new LockItem.Skill("building", 8)),
            new LockItem("minecraft:iron_pickaxe", new LockItem.Skill("building", 8)),
            new LockItem("minecraft:iron_axe", new LockItem.Skill("strength", 8), new LockItem.Skill("building", 8)),
            new LockItem("minecraft:iron_sword", new LockItem.Skill("strength", 8)),
            new LockItem("minecraft:golden_hoe", new LockItem.Skill("building", 6)),
            new LockItem("minecraft:golden_shovel", new LockItem.Skill("building", 6)),
            new LockItem("minecraft:golden_pickaxe", new LockItem.Skill("building", 6)),
            new LockItem("minecraft:golden_axe", new LockItem.Skill("building", 6), new LockItem.Skill("strength", 6)),
            new LockItem("minecraft:golden_sword", new LockItem.Skill("strength", 6)),
            new LockItem("minecraft:diamond_hoe", new LockItem.Skill("building", 16)),
            new LockItem("minecraft:diamond_shovel", new LockItem.Skill("building", 16)),
            new LockItem("minecraft:diamond_pickaxe", new LockItem.Skill("building", 16)),
            new LockItem("minecraft:diamond_axe", new LockItem.Skill("strength", 16), new LockItem.Skill("building", 16)),
            new LockItem("minecraft:diamond_sword", new LockItem.Skill("strength", 16)),
            new LockItem("minecraft:netherite_hoe", new LockItem.Skill("building", 24)),
            new LockItem("minecraft:netherite_shovel", new LockItem.Skill("building", 24)),
            new LockItem("minecraft:netherite_pickaxe", new LockItem.Skill("building", 24)),
            new LockItem("minecraft:netherite_axe", new LockItem.Skill("strength", 24), new LockItem.Skill("building", 24)),
            new LockItem("minecraft:netherite_sword", new LockItem.Skill("strength", 24)),
            new LockItem("minecraft:honey_bottle", new LockItem.Skill("constitution", 4)),
            new LockItem("minecraft:potion", new LockItem.Skill("fortune", 4)),
            new LockItem("minecraft:splash_potion", new LockItem.Skill("fortune", 6), new LockItem.Skill("dexterity", 6)),
            new LockItem("minecraft:lingering_potion", new LockItem.Skill("fortune", 6), new LockItem.Skill("magic", 6)),

            // Ars Nouveau - Spellbooks
            new LockItem("ars_nouveau:novice_spellbook", new LockItem.Skill("magic", 4)),
            new LockItem("ars_nouveau:apprentice_spellbook", new LockItem.Skill("magic", 12)),
            new LockItem("ars_nouveau:archmage_spellbook", new LockItem.Skill("magic", 24)),

            // Ars Nouveau - Casting Tools
            new LockItem("ars_nouveau:wand", new LockItem.Skill("magic", 6)),
            new LockItem("ars_nouveau:spell_bow", new LockItem.Skill("magic", 12), new LockItem.Skill("dexterity", 8)),
            new LockItem("ars_nouveau:caster_tome", new LockItem.Skill("magic", 16)),

            // Ars Nouveau - Spell Arrows
            new LockItem("ars_nouveau:amplify_arrow", new LockItem.Skill("dexterity", 8), new LockItem.Skill("magic", 8)),
            new LockItem("ars_nouveau:split_arrow", new LockItem.Skill("dexterity", 12), new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:pierce_arrow", new LockItem.Skill("dexterity", 12), new LockItem.Skill("magic", 10)),

            // Ars Nouveau - Sorcerer Armor
            new LockItem("ars_nouveau:sorcerer_boots", new LockItem.Skill("magic", 8), new LockItem.Skill("endurance", 4)),
            new LockItem("ars_nouveau:sorcerer_leggings", new LockItem.Skill("magic", 8), new LockItem.Skill("endurance", 4)),
            new LockItem("ars_nouveau:sorcerer_robes", new LockItem.Skill("magic", 8), new LockItem.Skill("endurance", 4)),
            new LockItem("ars_nouveau:sorcerer_hood", new LockItem.Skill("magic", 8), new LockItem.Skill("endurance", 4)),

            // Ars Nouveau - Arcanist Armor
            new LockItem("ars_nouveau:arcanist_boots", new LockItem.Skill("magic", 20), new LockItem.Skill("endurance", 12)),
            new LockItem("ars_nouveau:arcanist_leggings", new LockItem.Skill("magic", 20), new LockItem.Skill("endurance", 12)),
            new LockItem("ars_nouveau:arcanist_robes", new LockItem.Skill("magic", 20), new LockItem.Skill("endurance", 12)),
            new LockItem("ars_nouveau:arcanist_hood", new LockItem.Skill("magic", 20), new LockItem.Skill("endurance", 12)),

            // Ars Nouveau - Weapons & Shields
            new LockItem("ars_nouveau:enchanters_sword", new LockItem.Skill("magic", 12), new LockItem.Skill("strength", 8)),
            new LockItem("ars_nouveau:enchanters_shield", new LockItem.Skill("magic", 12), new LockItem.Skill("endurance", 8)),
            new LockItem("ars_nouveau:enchanters_mirror", new LockItem.Skill("magic", 16)),

            // Ars Nouveau - Curios / Accessories
            new LockItem("ars_nouveau:ring_of_lesser_discount", new LockItem.Skill("magic", 8)),
            new LockItem("ars_nouveau:ring_of_greater_discount", new LockItem.Skill("magic", 16)),
            new LockItem("ars_nouveau:amulet_of_mana_boost", new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:amulet_of_mana_regen", new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:belt_of_levitation", new LockItem.Skill("magic", 16)),
            new LockItem("ars_nouveau:belt_of_unstable_gifts", new LockItem.Skill("magic", 12), new LockItem.Skill("fortune", 8)),
            new LockItem("ars_nouveau:summoning_focus", new LockItem.Skill("magic", 16)),
            new LockItem("ars_nouveau:shapers_focus", new LockItem.Skill("magic", 20)),

            // Ars Nouveau - Crafting & Ritual Blocks
            new LockItem("ars_nouveau:scribes_table", new LockItem.Skill("wisdom", 6), new LockItem.Skill("magic", 4)),
            new LockItem("ars_nouveau:enchanting_apparatus", new LockItem.Skill("wisdom", 12), new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:imbuement_chamber", new LockItem.Skill("wisdom", 12), new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:rune_block", new LockItem.Skill("wisdom", 16), new LockItem.Skill("magic", 12)),
            new LockItem("ars_nouveau:arcane_core", new LockItem.Skill("wisdom", 20), new LockItem.Skill("magic", 16)),
            new LockItem("ars_nouveau:wixie_cauldron", new LockItem.Skill("wisdom", 14), new LockItem.Skill("magic", 12)),

            // Ars Nouveau - Source Management
            new LockItem("ars_nouveau:source_jar", new LockItem.Skill("magic", 6)),
            new LockItem("ars_nouveau:relay", new LockItem.Skill("magic", 10), new LockItem.Skill("intelligence", 8)),
            new LockItem("ars_nouveau:relay_splitter", new LockItem.Skill("magic", 14), new LockItem.Skill("intelligence", 10)),
            new LockItem("ars_nouveau:agronomic_sourcelink", new LockItem.Skill("magic", 8), new LockItem.Skill("intelligence", 8)),
            new LockItem("ars_nouveau:volcanic_sourcelink", new LockItem.Skill("magic", 10), new LockItem.Skill("intelligence", 8)),
            new LockItem("ars_nouveau:alchemical_sourcelink", new LockItem.Skill("magic", 12), new LockItem.Skill("intelligence", 10)),

            // Ars Nouveau - Familiar Charms
            new LockItem("ars_nouveau:starbuncle_charm", new LockItem.Skill("magic", 8)),
            new LockItem("ars_nouveau:bookwyrm_charm", new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:whirlisprig_charm", new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:wixie_charm", new LockItem.Skill("magic", 12)),
            new LockItem("ars_nouveau:drygmy_charm", new LockItem.Skill("magic", 14)),

            // Ars Nouveau - Utility Items
            new LockItem("ars_nouveau:warp_scroll", new LockItem.Skill("magic", 12)),
            new LockItem("ars_nouveau:void_jar", new LockItem.Skill("magic", 10)),
            new LockItem("ars_nouveau:dominion_rod", new LockItem.Skill("magic", 8), new LockItem.Skill("wisdom", 8)),
            new LockItem("ars_nouveau:runic_chalk", new LockItem.Skill("magic", 10), new LockItem.Skill("wisdom", 10)),
            new LockItem("ars_nouveau:spell_parchment", new LockItem.Skill("magic", 4), new LockItem.Skill("intelligence", 4)),

            // Ars Nouveau - Potion Flasks
            new LockItem("ars_nouveau:potion_flask", new LockItem.Skill("fortune", 6), new LockItem.Skill("magic", 6)),
            new LockItem("ars_nouveau:potion_flask_extend_time", new LockItem.Skill("fortune", 10), new LockItem.Skill("magic", 8)),
            new LockItem("ars_nouveau:potion_flask_amplify", new LockItem.Skill("fortune", 12), new LockItem.Skill("magic", 10)),

            // Apotheosis - Crafting Stations
            new LockItem("apotheosis:salvaging_table", new LockItem.Skill("building", 12), new LockItem.Skill("intelligence", 10)),
            new LockItem("apotheosis:simple_reforging_table", new LockItem.Skill("magic", 14), new LockItem.Skill("wisdom", 12)),
            new LockItem("apotheosis:reforging_table", new LockItem.Skill("magic", 18), new LockItem.Skill("wisdom", 16)),
            new LockItem("apotheosis:gem_cutting_table", new LockItem.Skill("building", 16), new LockItem.Skill("fortune", 12)),
            new LockItem("apotheosis:augmenting_table", new LockItem.Skill("magic", 22), new LockItem.Skill("intelligence", 18)),
            // Apotheosis - Enchanting Shelves
            new LockItem("apotheosis:hellshelf", new LockItem.Skill("magic", 12)),
            new LockItem("apotheosis:infused_hellshelf", new LockItem.Skill("magic", 16)),
            new LockItem("apotheosis:blazing_hellshelf", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 14)),
            new LockItem("apotheosis:glowing_hellshelf", new LockItem.Skill("magic", 16), new LockItem.Skill("intelligence", 12)),
            new LockItem("apotheosis:seashelf", new LockItem.Skill("magic", 12)),
            new LockItem("apotheosis:infused_seashelf", new LockItem.Skill("magic", 16)),
            new LockItem("apotheosis:crystal_seashelf", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 14)),
            new LockItem("apotheosis:heart_seashelf", new LockItem.Skill("magic", 20), new LockItem.Skill("intelligence", 16)),
            new LockItem("apotheosis:endshelf", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 16)),
            new LockItem("apotheosis:pearl_endshelf", new LockItem.Skill("magic", 22), new LockItem.Skill("intelligence", 18)),
            new LockItem("apotheosis:draconic_endshelf", new LockItem.Skill("magic", 26), new LockItem.Skill("intelligence", 22)),
            new LockItem("apotheosis:beeshelf", new LockItem.Skill("magic", 10), new LockItem.Skill("intelligence", 10)),
            new LockItem("apotheosis:melonshelf", new LockItem.Skill("magic", 10), new LockItem.Skill("intelligence", 10)),
            new LockItem("apotheosis:stoneshelf", new LockItem.Skill("magic", 10)),
            new LockItem("apotheosis:dormant_deepshelf", new LockItem.Skill("magic", 14)),
            new LockItem("apotheosis:deepshelf", new LockItem.Skill("magic", 16), new LockItem.Skill("intelligence", 14)),
            new LockItem("apotheosis:echoing_deepshelf", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 16)),
            new LockItem("apotheosis:library", new LockItem.Skill("magic", 20), new LockItem.Skill("intelligence", 18)),
            new LockItem("apotheosis:ender_library", new LockItem.Skill("magic", 26), new LockItem.Skill("intelligence", 22)),
            // Apotheosis - Unlocked Shelves & Rectifiers
            new LockItem("apotheosis:sightshelf", new LockItem.Skill("magic", 14), new LockItem.Skill("intelligence", 10)),
            new LockItem("apotheosis:sightshelf_t2", new LockItem.Skill("magic", 20), new LockItem.Skill("intelligence", 16)),
            new LockItem("apotheosis:filtering_shelf", new LockItem.Skill("magic", 14), new LockItem.Skill("intelligence", 10)),
            new LockItem("apotheosis:rectifier", new LockItem.Skill("magic", 14), new LockItem.Skill("intelligence", 10)),
            new LockItem("apotheosis:rectifier_t2", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 14)),
            new LockItem("apotheosis:rectifier_t3", new LockItem.Skill("magic", 24), new LockItem.Skill("intelligence", 20)),
            new LockItem("apotheosis:soul_touched_deepshelf", new LockItem.Skill("magic", 20), new LockItem.Skill("intelligence", 16)),
            new LockItem("apotheosis:treasure_shelf", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 14)),
            new LockItem("apotheosis:echoing_sculkshelf", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 16)),
            new LockItem("apotheosis:soul_touched_sculkshelf", new LockItem.Skill("magic", 20), new LockItem.Skill("intelligence", 16)),
            // Apotheosis - Sigils
            new LockItem("apotheosis:sigil_of_socketing", new LockItem.Skill("magic", 14), new LockItem.Skill("tinkering", 10)),
            new LockItem("apotheosis:sigil_of_enhancement", new LockItem.Skill("magic", 18), new LockItem.Skill("intelligence", 14)),
            new LockItem("apotheosis:sigil_of_rebirth", new LockItem.Skill("magic", 20), new LockItem.Skill("wisdom", 16)),
            new LockItem("apotheosis:sigil_of_withdrawal", new LockItem.Skill("magic", 14), new LockItem.Skill("dexterity", 10)),
            new LockItem("apotheosis:sigil_of_unnaming", new LockItem.Skill("magic", 10)),
            // Apotheosis - Tomes
            new LockItem("apotheosis:scrap_tome", new LockItem.Skill("intelligence", 10), new LockItem.Skill("magic", 8)),
            new LockItem("apotheosis:improved_scrap_tome", new LockItem.Skill("intelligence", 16), new LockItem.Skill("magic", 12)),
            new LockItem("apotheosis:extraction_tome", new LockItem.Skill("intelligence", 22), new LockItem.Skill("magic", 18)),
            new LockItem("apotheosis:weapon_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("strength", 6)),
            new LockItem("apotheosis:bow_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("dexterity", 6)),
            new LockItem("apotheosis:pickaxe_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("building", 6)),
            new LockItem("apotheosis:boots_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("dexterity", 6)),
            new LockItem("apotheosis:helmet_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("endurance", 6)),
            new LockItem("apotheosis:chestplate_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("endurance", 6)),
            new LockItem("apotheosis:leggings_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("endurance", 6)),
            new LockItem("apotheosis:fishing_tome", new LockItem.Skill("intelligence", 8), new LockItem.Skill("fortune", 6)),
            new LockItem("apotheosis:other_tome", new LockItem.Skill("intelligence", 10), new LockItem.Skill("wisdom", 8)),
            // Apotheosis - Boss Summoner & Unique Items
            new LockItem("apotheosis:boss_summoner", new LockItem.Skill("strength", 20), new LockItem.Skill("magic", 16)),
            new LockItem("apotheosis:lucky_foot", new LockItem.Skill("fortune", 12)),
            new LockItem("apotheosis:potion_charm", new LockItem.Skill("magic", 14), new LockItem.Skill("intelligence", 10)),
            new LockItem("apotheosis:ender_lead", new LockItem.Skill("magic", 16), new LockItem.Skill("wisdom", 12)),
            new LockItem("apotheosis:infused_breath", new LockItem.Skill("magic", 24), new LockItem.Skill("constitution", 18)),
            new LockItem("apotheosis:warden_tendril", new LockItem.Skill("endurance", 22), new LockItem.Skill("magic", 16)),
            new LockItem("apotheosis:inert_trident", new LockItem.Skill("strength", 16), new LockItem.Skill("dexterity", 12)),
            // Apotheosis - Rarity Materials (matching affix tier requirements)
            new LockItem("apotheosis:uncommon_material", new LockItem.Skill("fortune", 4)),
            new LockItem("apotheosis:rare_material", new LockItem.Skill("fortune", 10)),
            new LockItem("apotheosis:epic_material", new LockItem.Skill("fortune", 18)),
            new LockItem("apotheosis:mythic_material", new LockItem.Skill("fortune", 26)),
            new LockItem("apotheosis:ancient_material", new LockItem.Skill("fortune", 32)),

            // --- Cataclysm - Boss Weapons ---
            new LockItem("cataclysm:coral_spear", new LockItem.Skill("strength", 16), new LockItem.Skill("dexterity", 10)),
            new LockItem("cataclysm:gauntlet_of_bulwark", new LockItem.Skill("strength", 20), new LockItem.Skill("endurance", 16)),
            new LockItem("cataclysm:void_forge", new LockItem.Skill("strength", 24), new LockItem.Skill("building", 18)),
            new LockItem("cataclysm:infernal_forge", new LockItem.Skill("strength", 26), new LockItem.Skill("building", 20)),
            new LockItem("cataclysm:ancient_spear", new LockItem.Skill("strength", 26), new LockItem.Skill("dexterity", 20)),
            new LockItem("cataclysm:astrape", new LockItem.Skill("strength", 28), new LockItem.Skill("magic", 24)),
            // Cataclysm - Ignitium Armor
            new LockItem("cataclysm:ignitium_helmet", new LockItem.Skill("endurance", 28), new LockItem.Skill("constitution", 22)),
            new LockItem("cataclysm:ignitium_chestplate", new LockItem.Skill("endurance", 28), new LockItem.Skill("constitution", 22)),
            new LockItem("cataclysm:ignitium_leggings", new LockItem.Skill("endurance", 28), new LockItem.Skill("constitution", 22)),
            new LockItem("cataclysm:ignitium_boots", new LockItem.Skill("endurance", 28), new LockItem.Skill("constitution", 22)),
            // Cataclysm - Cursium Armor
            new LockItem("cataclysm:cursium_helmet", new LockItem.Skill("endurance", 26), new LockItem.Skill("constitution", 20)),
            new LockItem("cataclysm:cursium_chestplate", new LockItem.Skill("endurance", 26), new LockItem.Skill("constitution", 20)),
            new LockItem("cataclysm:cursium_leggings", new LockItem.Skill("endurance", 26), new LockItem.Skill("constitution", 20)),
            new LockItem("cataclysm:cursium_boots", new LockItem.Skill("endurance", 26), new LockItem.Skill("constitution", 20)),
            // Cataclysm - Boss Altars
            new LockItem("cataclysm:altar_of_fire", new LockItem.Skill("building", 20), new LockItem.Skill("magic", 16)),
            new LockItem("cataclysm:altar_of_abyss", new LockItem.Skill("building", 22), new LockItem.Skill("magic", 18)),
            new LockItem("cataclysm:altar_of_void", new LockItem.Skill("building", 24), new LockItem.Skill("magic", 20)),
            new LockItem("cataclysm:altar_of_amethyst", new LockItem.Skill("building", 26), new LockItem.Skill("magic", 22)),
            // Cataclysm - Endgame Weapons (Unbreakable)
            new LockItem("cataclysm:ceraunus", new LockItem.Skill("strength", 32), new LockItem.Skill("magic", 22)),
            new LockItem("cataclysm:soul_render", new LockItem.Skill("strength", 30), new LockItem.Skill("magic", 20)),
            new LockItem("cataclysm:the_incinerator", new LockItem.Skill("strength", 28), new LockItem.Skill("magic", 18)),
            new LockItem("cataclysm:zweiender", new LockItem.Skill("strength", 26), new LockItem.Skill("dexterity", 18)),
            new LockItem("cataclysm:gauntlet_of_guard", new LockItem.Skill("strength", 22), new LockItem.Skill("endurance", 18)),
            new LockItem("cataclysm:gauntlet_of_maelstrom", new LockItem.Skill("strength", 24), new LockItem.Skill("magic", 18)),
            new LockItem("cataclysm:meat_shredder", new LockItem.Skill("strength", 22), new LockItem.Skill("dexterity", 14)),
            new LockItem("cataclysm:tidal_claws", new LockItem.Skill("strength", 20), new LockItem.Skill("dexterity", 14)),
            new LockItem("cataclysm:the_annihilator", new LockItem.Skill("strength", 20), new LockItem.Skill("intelligence", 14)),
            new LockItem("cataclysm:the_immolator", new LockItem.Skill("strength", 20), new LockItem.Skill("magic", 14)),
            // Cataclysm - Ranged/Special Weapons (Unbreakable)
            new LockItem("cataclysm:cursed_bow", new LockItem.Skill("dexterity", 26), new LockItem.Skill("magic", 20)),
            new LockItem("cataclysm:void_jaw", new LockItem.Skill("dexterity", 24), new LockItem.Skill("magic", 18)),
            new LockItem("cataclysm:laser_gatling", new LockItem.Skill("dexterity", 22), new LockItem.Skill("intelligence", 16)),
            new LockItem("cataclysm:wrath_of_the_desert", new LockItem.Skill("magic", 26), new LockItem.Skill("strength", 20)),
            // Cataclysm - Mid-Tier Weapons
            new LockItem("cataclysm:coral_bardiche", new LockItem.Skill("strength", 18), new LockItem.Skill("dexterity", 12)),
            new LockItem("cataclysm:black_steel_sword", new LockItem.Skill("strength", 14)),
            new LockItem("cataclysm:black_steel_axe", new LockItem.Skill("strength", 16), new LockItem.Skill("building", 12)),
            new LockItem("cataclysm:khopesh", new LockItem.Skill("strength", 14), new LockItem.Skill("dexterity", 10)),
            new LockItem("cataclysm:athame", new LockItem.Skill("dexterity", 12)),
            // Cataclysm - Shields
            new LockItem("cataclysm:bulwark_of_the_flame", new LockItem.Skill("endurance", 28), new LockItem.Skill("constitution", 24)),
            new LockItem("cataclysm:black_steel_targe", new LockItem.Skill("endurance", 14), new LockItem.Skill("constitution", 10)),
            new LockItem("cataclysm:azure_sea_shield", new LockItem.Skill("endurance", 12), new LockItem.Skill("constitution", 8)),
            // Cataclysm - Ungated Armor
            new LockItem("cataclysm:bone_reptile_helmet", new LockItem.Skill("endurance", 20), new LockItem.Skill("constitution", 14)),
            new LockItem("cataclysm:bone_reptile_chestplate", new LockItem.Skill("endurance", 20), new LockItem.Skill("constitution", 14)),
            new LockItem("cataclysm:ignitium_elytra_chestplate", new LockItem.Skill("endurance", 30), new LockItem.Skill("dexterity", 24)),
            // Cataclysm - Black Steel Tools
            new LockItem("cataclysm:black_steel_pickaxe", new LockItem.Skill("building", 14), new LockItem.Skill("strength", 10)),
            new LockItem("cataclysm:black_steel_shovel", new LockItem.Skill("building", 14)),
            new LockItem("cataclysm:black_steel_hoe", new LockItem.Skill("building", 14)),
            // Cataclysm - Crafting Station
            new LockItem("cataclysm:mechanical_fusion_anvil", new LockItem.Skill("building", 24), new LockItem.Skill("tinkering", 18)),
            // Cataclysm - Special Items & Boss Drops
            new LockItem("cataclysm:void_assault_shoulder_weapon", new LockItem.Skill("strength", 26), new LockItem.Skill("intelligence", 20)),
            new LockItem("cataclysm:wither_assault_shoulder_weapon", new LockItem.Skill("strength", 26), new LockItem.Skill("magic", 20)),
            new LockItem("cataclysm:final_fractal", new LockItem.Skill("magic", 28), new LockItem.Skill("intelligence", 22)),
            new LockItem("cataclysm:sandstorm_in_a_bottle", new LockItem.Skill("magic", 22), new LockItem.Skill("dexterity", 16)),
            new LockItem("cataclysm:lava_power_cell", new LockItem.Skill("intelligence", 20), new LockItem.Skill("magic", 16)),
            new LockItem("cataclysm:chain_of_soul_binding", new LockItem.Skill("magic", 22), new LockItem.Skill("wisdom", 16)),
            new LockItem("cataclysm:abyssal_sacrifice", new LockItem.Skill("magic", 20), new LockItem.Skill("constitution", 16)),
            new LockItem("cataclysm:abyssal_egg", new LockItem.Skill("magic", 24), new LockItem.Skill("constitution", 18)),
            new LockItem("cataclysm:strange_key", new LockItem.Skill("fortune", 16), new LockItem.Skill("intelligence", 12)),
            // Cataclysm - Curio Items
            new LockItem("cataclysm:chitin_claw", new LockItem.Skill("strength", 20), new LockItem.Skill("dexterity", 16)),
            new LockItem("cataclysm:necklace_of_the_desert", new LockItem.Skill("fortune", 18), new LockItem.Skill("magic", 14)),
            new LockItem("cataclysm:sticky_gloves", new LockItem.Skill("dexterity", 10)),
            // Cataclysm - Smithing Templates
            new LockItem("cataclysm:ignitium_upgrade_smithing_template", new LockItem.Skill("building", 26), new LockItem.Skill("intelligence", 20)),
            new LockItem("cataclysm:cursium_upgrade_smithing_template", new LockItem.Skill("building", 24), new LockItem.Skill("intelligence", 18)),
            // Cataclysm - Epic Crafting Materials
            new LockItem("cataclysm:cursium_ingot", new LockItem.Skill("fortune", 22), new LockItem.Skill("building", 16)),
            new LockItem("cataclysm:ignitium_ingot", new LockItem.Skill("fortune", 26), new LockItem.Skill("building", 20)),
            new LockItem("cataclysm:witherite_ingot", new LockItem.Skill("fortune", 28), new LockItem.Skill("building", 22)),
            new LockItem("cataclysm:enderite_ingot", new LockItem.Skill("fortune", 24), new LockItem.Skill("magic", 18)),
            new LockItem("cataclysm:essence_of_the_storm", new LockItem.Skill("magic", 24), new LockItem.Skill("fortune", 18)),
            new LockItem("cataclysm:void_core", new LockItem.Skill("magic", 22), new LockItem.Skill("intelligence", 16)),
            // Cataclysm - Epic Decorative & Boss Blocks
            new LockItem("cataclysm:netherite_effigy", new LockItem.Skill("building", 22), new LockItem.Skill("magic", 16)),
            new LockItem("cataclysm:goddess_statue", new LockItem.Skill("building", 24), new LockItem.Skill("magic", 20)),
            new LockItem("cataclysm:cursed_tombstone", new LockItem.Skill("magic", 18), new LockItem.Skill("wisdom", 12)),
            new LockItem("cataclysm:boss_respawner", new LockItem.Skill("magic", 26), new LockItem.Skill("strength", 22)),
            new LockItem("cataclysm:door_of_seal", new LockItem.Skill("magic", 22), new LockItem.Skill("building", 18)),

            // --- Mowzie's Mobs - Boss Drops ---
            new LockItem("mowziesmobs:wrought_helmet", new LockItem.Skill("endurance", 22), new LockItem.Skill("strength", 18)),
            new LockItem("mowziesmobs:naga_fang_dagger", new LockItem.Skill("dexterity", 16), new LockItem.Skill("strength", 12)),
            new LockItem("mowziesmobs:ice_crystal", new LockItem.Skill("magic", 22), new LockItem.Skill("constitution", 18)),
            new LockItem("mowziesmobs:earthrend_gauntlet", new LockItem.Skill("strength", 20), new LockItem.Skill("building", 16)),
            // Mowzie's - Umvuthana Masks
            new LockItem("mowziesmobs:umvuthana_mask_fury", new LockItem.Skill("magic", 18), new LockItem.Skill("strength", 14)),
            new LockItem("mowziesmobs:umvuthana_mask_bliss", new LockItem.Skill("magic", 18), new LockItem.Skill("wisdom", 14)),
            new LockItem("mowziesmobs:umvuthana_mask_rage", new LockItem.Skill("magic", 18), new LockItem.Skill("strength", 14)),
            new LockItem("mowziesmobs:umvuthana_mask_fear", new LockItem.Skill("magic", 18), new LockItem.Skill("endurance", 14)),
            new LockItem("mowziesmobs:umvuthana_mask_faith", new LockItem.Skill("magic", 18), new LockItem.Skill("wisdom", 14)),
            new LockItem("mowziesmobs:umvuthana_mask_misery", new LockItem.Skill("magic", 18), new LockItem.Skill("constitution", 14)),
            // Mowzie's - Geomancer Armor
            new LockItem("mowziesmobs:geomancer_beads", new LockItem.Skill("magic", 20), new LockItem.Skill("wisdom", 16)),
            new LockItem("mowziesmobs:geomancer_robe", new LockItem.Skill("magic", 20), new LockItem.Skill("wisdom", 16)),
            new LockItem("mowziesmobs:geomancer_belt", new LockItem.Skill("magic", 20), new LockItem.Skill("wisdom", 16)),
            new LockItem("mowziesmobs:geomancer_sandals", new LockItem.Skill("magic", 20), new LockItem.Skill("wisdom", 16)),

            // --- Enigmatic Legacy - Artifacts ---
            new LockItem("enigmaticlegacy:berserk_charm", new LockItem.Skill("strength", 16), new LockItem.Skill("constitution", 12)),
            new LockItem("enigmaticlegacy:cursed_ring", new LockItem.Skill("wisdom", 18), new LockItem.Skill("constitution", 14)),
            new LockItem("enigmaticlegacy:astral_breaker", new LockItem.Skill("strength", 26), new LockItem.Skill("magic", 22)),
            new LockItem("enigmaticlegacy:cosmic_heart", new LockItem.Skill("magic", 28), new LockItem.Skill("constitution", 24)),

            // --- Nature's Aura - Crafting & Equipment ---
            new LockItem("naturesaura:nature_altar", new LockItem.Skill("wisdom", 8), new LockItem.Skill("building", 6)),
            new LockItem("naturesaura:infused_iron_pickaxe", new LockItem.Skill("building", 12), new LockItem.Skill("wisdom", 8)),
            new LockItem("naturesaura:infused_iron_axe", new LockItem.Skill("strength", 12), new LockItem.Skill("wisdom", 8)),
            new LockItem("naturesaura:infused_iron_sword", new LockItem.Skill("strength", 12), new LockItem.Skill("wisdom", 8)),
            new LockItem("naturesaura:infused_iron_shovel", new LockItem.Skill("building", 10), new LockItem.Skill("wisdom", 6)),
            new LockItem("naturesaura:infused_iron_hoe", new LockItem.Skill("building", 10), new LockItem.Skill("wisdom", 6)),
            new LockItem("naturesaura:infused_iron_helmet", new LockItem.Skill("endurance", 12), new LockItem.Skill("wisdom", 8)),
            new LockItem("naturesaura:infused_iron_chest", new LockItem.Skill("endurance", 12), new LockItem.Skill("wisdom", 8)),
            new LockItem("naturesaura:infused_iron_pants", new LockItem.Skill("endurance", 12), new LockItem.Skill("wisdom", 8)),
            new LockItem("naturesaura:infused_iron_shoes", new LockItem.Skill("endurance", 12), new LockItem.Skill("wisdom", 8)),

            // --- Farmer's Delight - Tools & Equipment ---
            new LockItem("farmersdelight:cooking_pot", new LockItem.Skill("intelligence", 8), new LockItem.Skill("building", 6)),
            new LockItem("farmersdelight:cutting_board", new LockItem.Skill("intelligence", 6)),
            new LockItem("farmersdelight:skillet", new LockItem.Skill("strength", 6), new LockItem.Skill("intelligence", 8)),
            new LockItem("farmersdelight:iron_knife", new LockItem.Skill("dexterity", 8), new LockItem.Skill("strength", 6)),
            new LockItem("farmersdelight:golden_knife", new LockItem.Skill("dexterity", 6), new LockItem.Skill("strength", 4)),
            new LockItem("farmersdelight:diamond_knife", new LockItem.Skill("dexterity", 16), new LockItem.Skill("strength", 12)),
            new LockItem("farmersdelight:netherite_knife", new LockItem.Skill("dexterity", 24), new LockItem.Skill("strength", 18)),

            // --- Minecolonies - Management Tools ---
            new LockItem("minecolonies:supplycampdeployer", new LockItem.Skill("intelligence", 4), new LockItem.Skill("building", 4)),
            new LockItem("minecolonies:supplychestdeployer", new LockItem.Skill("intelligence", 6), new LockItem.Skill("building", 6)),
            new LockItem("minecolonies:build_goggles", new LockItem.Skill("building", 8)),
            new LockItem("minecolonies:scepterpermission", new LockItem.Skill("intelligence", 12)),
            new LockItem("minecolonies:scepterguard", new LockItem.Skill("intelligence", 14), new LockItem.Skill("strength", 10)),
            new LockItem("minecolonies:scepterbeekeeper", new LockItem.Skill("intelligence", 10)),
            new LockItem("minecolonies:blockhutbuilder", new LockItem.Skill("building", 10), new LockItem.Skill("intelligence", 8)),

            // --- Stalwart Dungeons - Weapons ---
            new LockItem("stalwart_dungeons:chorundum_sword", new LockItem.Skill("strength", 20)),
            new LockItem("stalwart_dungeons:chorundum_axe", new LockItem.Skill("strength", 22), new LockItem.Skill("building", 16)),
            new LockItem("stalwart_dungeons:tungsten_sword", new LockItem.Skill("strength", 16)),
            new LockItem("stalwart_dungeons:tungsten_hammer", new LockItem.Skill("strength", 22), new LockItem.Skill("endurance", 16)),
            new LockItem("stalwart_dungeons:tungsten_axe", new LockItem.Skill("strength", 18), new LockItem.Skill("building", 12)),
            new LockItem("stalwart_dungeons:nether_hammer", new LockItem.Skill("strength", 26), new LockItem.Skill("endurance", 20)),
            new LockItem("stalwart_dungeons:netherite_hammer", new LockItem.Skill("strength", 24), new LockItem.Skill("endurance", 18)),
            new LockItem("stalwart_dungeons:diamond_hammer", new LockItem.Skill("strength", 20), new LockItem.Skill("endurance", 14)),
            new LockItem("stalwart_dungeons:iron_hammer", new LockItem.Skill("strength", 12), new LockItem.Skill("endurance", 8)),
            new LockItem("stalwart_dungeons:golden_hammer", new LockItem.Skill("strength", 8)),
            new LockItem("stalwart_dungeons:stone_hammer", new LockItem.Skill("strength", 10)),
            new LockItem("stalwart_dungeons:wooden_hammer", new LockItem.Skill("strength", 4)),
            new LockItem("stalwart_dungeons:awful_dagger", new LockItem.Skill("dexterity", 14), new LockItem.Skill("magic", 10)),
            // Stalwart Dungeons - Tools
            new LockItem("stalwart_dungeons:chorundum_pickaxe", new LockItem.Skill("building", 20)),
            new LockItem("stalwart_dungeons:chorundum_shovel", new LockItem.Skill("building", 20)),
            new LockItem("stalwart_dungeons:tungsten_pickaxe", new LockItem.Skill("building", 16)),
            new LockItem("stalwart_dungeons:tungsten_shovel", new LockItem.Skill("building", 16)),
            // Stalwart Dungeons - Armor
            new LockItem("stalwart_dungeons:chorundum_armor_helmet", new LockItem.Skill("endurance", 22), new LockItem.Skill("constitution", 16)),
            new LockItem("stalwart_dungeons:chorundum_armor_chestplate", new LockItem.Skill("endurance", 22), new LockItem.Skill("constitution", 16)),
            new LockItem("stalwart_dungeons:chorundum_armor_leggings", new LockItem.Skill("endurance", 22), new LockItem.Skill("constitution", 16)),
            new LockItem("stalwart_dungeons:chorundum_armor_boots", new LockItem.Skill("endurance", 22), new LockItem.Skill("constitution", 16)),
            new LockItem("stalwart_dungeons:tungsten_helmet", new LockItem.Skill("endurance", 18), new LockItem.Skill("constitution", 12)),
            new LockItem("stalwart_dungeons:tungsten_chestplate", new LockItem.Skill("endurance", 18), new LockItem.Skill("constitution", 12)),
            new LockItem("stalwart_dungeons:tungsten_leggings", new LockItem.Skill("endurance", 18), new LockItem.Skill("constitution", 12)),
            new LockItem("stalwart_dungeons:tungsten_boots", new LockItem.Skill("endurance", 18), new LockItem.Skill("constitution", 12)),
            new LockItem("stalwart_dungeons:warted_tungsten_helmet", new LockItem.Skill("endurance", 20), new LockItem.Skill("constitution", 14)),
            new LockItem("stalwart_dungeons:warted_tungsten_chestplate", new LockItem.Skill("endurance", 20), new LockItem.Skill("constitution", 14)),
            new LockItem("stalwart_dungeons:warted_tungsten_leggings", new LockItem.Skill("endurance", 20), new LockItem.Skill("constitution", 14)),
            new LockItem("stalwart_dungeons:warted_tungsten_boots", new LockItem.Skill("endurance", 20), new LockItem.Skill("constitution", 14)),

            // --- Nichirin Dynasty - Katanas ---
            new LockItem("nichirin_dynasty:tanjirokatanav_2", new LockItem.Skill("strength", 30), new LockItem.Skill("dexterity", 22)),
            new LockItem("nichirin_dynasty:giyuukatana", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 20)),
            new LockItem("nichirin_dynasty:obanaikatana", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 20)),
            new LockItem("nichirin_dynasty:rengokukatana", new LockItem.Skill("strength", 28), new LockItem.Skill("magic", 20)),
            new LockItem("nichirin_dynasty:sanemikatana", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 20)),
            new LockItem("nichirin_dynasty:inosukekatana", new LockItem.Skill("strength", 28), new LockItem.Skill("constitution", 20)),
            new LockItem("nichirin_dynasty:mitsurikatana", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 20)),
            new LockItem("nichirin_dynasty:tanjirokatana", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 20)),
            new LockItem("nichirin_dynasty:tokitokatana", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 20)),
            new LockItem("nichirin_dynasty:zenitsukatana", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 22)),
            new LockItem("nichirin_dynasty:tengenblade", new LockItem.Skill("strength", 28), new LockItem.Skill("dexterity", 20)),
            new LockItem("nichirin_dynasty:gyomeimace", new LockItem.Skill("strength", 28), new LockItem.Skill("constitution", 20)),
            new LockItem("nichirin_dynasty:gyomeiaxe", new LockItem.Skill("strength", 28), new LockItem.Skill("building", 20)),
            new LockItem("nichirin_dynasty:genyakatana", new LockItem.Skill("strength", 24), new LockItem.Skill("dexterity", 16)),
            new LockItem("nichirin_dynasty:nichirinkatana", new LockItem.Skill("strength", 24), new LockItem.Skill("dexterity", 16)),
            new LockItem("nichirin_dynasty:shinobukatana", new LockItem.Skill("strength", 24), new LockItem.Skill("dexterity", 18)),

            // --- Bosses of Mass Destruction ---
            new LockItem("bosses_of_mass_destruction:earthdive_spear", new LockItem.Skill("strength", 22), new LockItem.Skill("dexterity", 16)),
            new LockItem("bosses_of_mass_destruction:obsidian_heart", new LockItem.Skill("magic", 22), new LockItem.Skill("constitution", 16)),
            new LockItem("bosses_of_mass_destruction:ancient_anima", new LockItem.Skill("magic", 24), new LockItem.Skill("wisdom", 18)),
            new LockItem("bosses_of_mass_destruction:blazing_eye", new LockItem.Skill("magic", 22), new LockItem.Skill("strength", 16)),
            new LockItem("bosses_of_mass_destruction:brimstone_nectar", new LockItem.Skill("magic", 20), new LockItem.Skill("constitution", 14)),
            new LockItem("bosses_of_mass_destruction:crystal_fruit", new LockItem.Skill("fortune", 18), new LockItem.Skill("magic", 14)),
            new LockItem("bosses_of_mass_destruction:void_thorn", new LockItem.Skill("magic", 22), new LockItem.Skill("endurance", 16)),

            // --- Siege Machines ---
            new LockItem("siegemachines:ballista", new LockItem.Skill("building", 18), new LockItem.Skill("strength", 14)),
            new LockItem("siegemachines:battering_ram", new LockItem.Skill("building", 16), new LockItem.Skill("strength", 12)),
            new LockItem("siegemachines:catapult", new LockItem.Skill("building", 16), new LockItem.Skill("strength", 12)),
            new LockItem("siegemachines:culverin", new LockItem.Skill("building", 20), new LockItem.Skill("intelligence", 16)),
            new LockItem("siegemachines:mortar", new LockItem.Skill("building", 18), new LockItem.Skill("intelligence", 14)),
            new LockItem("siegemachines:trebuchet", new LockItem.Skill("building", 20), new LockItem.Skill("strength", 16)),
            new LockItem("siegemachines:siege_ladder", new LockItem.Skill("building", 10)),
            new LockItem("siegemachines:siege_workbench", new LockItem.Skill("building", 12), new LockItem.Skill("tinkering", 8))

            // Note: Locks, Samurai Dynasty, More Vanilla, and Jewelcraft items are generated programmatically
    );
}
